org: shamariyan
app: serverlesscicd
service: serverlesscicd
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  mainLambdaFunction:
    handler: main.mainFunction
    url:
      cors:
        allowedOrigins:
          - https://webhook-endpoint.herokuapp.com
        allowedHeaders:
          - Content-Type
          - Authorization
        allowedMethods:
          - GET
    events:
      - httpApi: '*'
