org: shamariyan
app: serverlesscicd
service: serverlesscicd
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  mainLambdaFunction:
    handler: main.mainFunction
    url: cors:true
    events:
      - httpApi: '*'
  secondaryLambdaFunction:
    handler: secondary.secondaryFunction
    url: cors:true
    events:
      - httpApi: '*'
