org: shamariyan
app: serverlesscicd
service: serverlesscicd
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  qr8InitialLambdaFunctions:
    handler: main.main
    url:
      cors: true
    events:
      - httpApi: '*'
