org: shamariyan
app: serverlesscicd
service: serverlesscicd
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  secondaryLambdaFunction:
    handler: tokenCreation.authTokenCreation
    url:
      cors: true
    events:
      - httpApi: '*'
